---
# Setup LAMP Stack
- hosts: lampserver 
  tasks:
    - name: install lamp stack
      become: yes
      become_user: root   
      apt:
        pkg:
          - apache2
          - mysql-server
          - php 
          - php-mysql
        state: present
        update_cache: yes

    - name: start apache service
      become: yes
      become_user: root    
      service:
        name: apache2
        state: started
        enabled: yes

    - name: start mysql service
      become: yes
      become_user: root   
      service:
        name: mysql
        state: started
        enabled: yes

    - name: create target directory
      file: path=/var/www/html state=directory mode=0755

    
    - name: Clone full repo
      become: yes
      git:
        repo: 'https://github.com/Sheetal-Shetty/AnsibleWorkUpdated.git'
        dest: /tmp/
        version: master
    
    - name: Copy only multipurpose folder to web root
      become: yes
      copy:
        src: /tmp/AnsibleWorkUpdated/lampansible/multipurpose/
        dest: /var/www/html/
    # - name: deploy index.html
    #   become: yes
    #   become_user: root    
    #   copy:
    #     #src: /home/ansible/lampansible/multipurpose/
    #     src: https://github.com/Sheetal-Shetty/AnsibleWorkUpdated/tree/master/lampansible/multipurpose
    #     dest: /var/www/html

        

