---
# Setup LAMP Stack
- hosts: lampserver 
  tasks:
    - name: install lamp stack
      become: yes
      become_user: root   
      apt:
        pkg:
          - apache2
          - mysql-server
          - php 
          - php-mysql
        state: present
        update_cache: yes

    - name: start apache service
      become: yes
      become_user: root    
      service:
        name: apache2
        state: started
        enabled: yes

    - name: start mysql service
      become: yes
      become_user: root   
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Change Apache DocumentRoot to /var/www/html
      become: yes
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '^\s*DocumentRoot\s+'
        line: 'DocumentRoot /var/www/html'
        backup: yes
    - name: Restart apache using service module
      become: yes
      service:
        name: apache2
        state: restarted    


    - name: create target directory
      file: path=/var/www/html state=directory mode=0755
    
    # - name: Clone full repo
    #   become: yes
    #   git:
    #     repo: 'https://github.com/Sheetal-Shetty/AnsibleWorkUpdated.git'
    #     dest: /tmp/
    #     version: master
    
    # - name: Copy only multipurpose folder to web root
    #   become: yes
    #   copy:
    #     src: /tmp/AnsibleWorkUpdated/lampansible/multipurpose/
    #     dest: /var/www/html/

    - name: Download website archive
      become: yes
      get_url:
        url: https://github.com/Sheetal-Shetty/AnsibleWorkUpdated/archive/refs/heads/master.zip
        dest: /tmp/AnsibleWorkUpdated-master.zip

    - name: Extract website files
      become: yes
      unarchive:
        src: /tmp/AnsibleWorkUpdated-master.zip
        dest: /tmp/
        remote_src: yes

    - name: deploy index.html
      become: yes
#      become_user: root    
      copy:
        src: /tmp/AnsibleWorkUpdated-master/lampansible/multipurpose/
        dest: /var/www/html
        remote_src: yes 

    # - name: deploy index.html
    #   become: yes
    #   become_user: root    
    #   copy:
    #     #src: /home/ansible/lampansible/multipurpose/
    #     src: https://github.com/Sheetal-Shetty/AnsibleWorkUpdated/tree/master/lampansible/multipurpose
    #     dest: /var/www/html

        

