---
# Setup LAMP Stack
- hosts: lampserver 
  tasks:
    - name: install lamp stack
      become: yes
      become_user: root   
      apt:
        pkg:
          - apache2
          - mysql-server
          - php 
          - php-mysql
        state: present
        update_cache: yes

    - name: start apache service
      become: yes
      become_user: root    
      service:
        name: apache2
        state: started
        enabled: yes

    - name: start mysql service
      become: yes
      become_user: root   
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Change Apache DocumentRoot to /var/www/html
      become: yes
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '^\s*DocumentRoot\s+'
        line: 'DocumentRoot /var/www/html'
        backup: yes
    - name: Restart apache using service module
      become: yes
      service:
        name: apache2
        state: restarted    
    - name: create target directory
      file: path=/var/www/html state=directory mode=0755
    - name: Download website archive
      become: yes
      get_url:
        url: https://github.com/Sheetal-Shetty/AnsibleWorkUpdated/archive/refs/heads/master.zip
        dest: /tmp/AnsibleWorkUpdated-master.zip

    - name: Extract website files
      become: yes
      unarchive:
        src: /tmp/AnsibleWorkUpdated-master.zip
        dest: /tmp/
        remote_src: yes

    - name: deploy index.html
      become: yes
#      become_user: root    
      copy:
        src: /tmp/AnsibleWorkUpdated-master/lampansible/index.html
        dest: /var/www/html/index.html
        remote_src: yes 
    # - name: deploy index.html
    #   become: yes
    #   become_user: root    
    #   copy:
    #     src: /home/ansible/lampansible/index.html
    #     dest: /var/www/html/index.html

